import { TAbstractFile, TFile, TFolder } from "obsidian";

import {
  formatVaultFolderLabel,
  getVaultFolderPath
} from "../util/vaultPath";

export const MAX_CONTEXT_CHARS = 20000;
export const MAX_DIRECTORY_CONTEXT_ITEMS = 80;
export const MAX_MENTIONED_FILES = 5;
export const MAX_PDF_CONTEXT_BYTES = 50 * 1024 * 1024;
export const MAX_SIDEKICK_PROFILE_INCLUDES = 8;

export const TEXT_CONTEXT_EXTENSIONS = new Set([
  "bib",
  "csv",
  "json",
  "latex",
  "md",
  "mmd",
  "tex",
  "txt",
  "yaml",
  "yml"
]);

export function formatPromptContext(
  label: string,
  filePath: string,
  text: string
): string {
  return [
    `<obsidian-context label="${label}" path="${filePath}">`,
    text,
    "</obsidian-context>"
  ].join("\n");
}

export function limitContextText(value: string): string {
  if (value.length <= MAX_CONTEXT_CHARS) {
    return value;
  }

  return `${value.slice(0, MAX_CONTEXT_CHARS)}\n\n[Context truncated to ${MAX_CONTEXT_CHARS.toLocaleString()} characters.]`;
}

export function getVaultGroundingInstructions(): string {
  return [
    "<vault-grounding-instructions>",
    "Use only the Obsidian context blocks supplied in this prompt as authoritative vault/project evidence.",
    "Tool-style context blocks such as Vault search, Related-note search, Safe command output, Fetched URL, and Internal link suggestions are generated by the plugin before the model runs.",
    "Do not invent vault files, sibling files, folder contents, citations, or code paths that are not present in the supplied file contents or directory listings.",
    "When asked what files exist in a folder, answer from the supplied Vault directory listing. If the listing does not include a file, say it is not present in the provided listing.",
    "</vault-grounding-instructions>"
  ].join("\n");
}

export function getEditProposalInstructions(): string {
  return [
    "<local-sidekick-edit-format>",
    "If you propose changes to vault files, include each full-file replacement in this exact fenced format:",
    "```agent-edit",
    "path: path/inside/vault.md",
    "---",
    "replacement file contents",
    "```",
    "Use this format for reviewed note creation, note updates, frontmatter updates, move/rename notes expressed as replacement files, and conservative internal-linking suggestions.",
    "Do not claim that edits have been applied. The dashboard will show a diff and require approval.",
    "</local-sidekick-edit-format>"
  ].join("\n");
}

export function canReadMentionedFileAsText(file: TFile): boolean {
  return TEXT_CONTEXT_EXTENSIONS.has(file.extension.toLowerCase());
}

export function formatMentionedAttachmentContext(
  file: TFile,
  warning?: string
): string {
  const extension = file.extension || "none";
  const size = Number.isFinite(file.stat.size)
    ? `${file.stat.size.toLocaleString()} bytes`
    : "unknown";

  return [
    `Path: ${file.path}`,
    `Extension: ${extension}`,
    `Size: ${size}`,
    "",
    "This file was referenced from the vault but its contents were not extracted as text.",
    "For PDFs or other binary attachments, do not infer the document contents unless another extracted text context is supplied.",
    warning ? `Warning: ${warning}` : ""
  ].filter(Boolean).join("\n");
}

export function formatVaultDirectoryContext(
  referencedFile: TFile,
  loadedFiles: TAbstractFile[]
): string {
  const folderPath = getVaultFolderPath(referencedFile.path);
  const directChildren = loadedFiles
    .filter((item) => item.path !== folderPath)
    .filter((item) => getVaultFolderPath(item.path) === folderPath)
    .sort(compareVaultFiles);
  const folders = directChildren.filter(
    (item): item is TFolder => item instanceof TFolder
  );
  const files = directChildren.filter(
    (item): item is TFile => item instanceof TFile
  );
  const markdownFiles = files.filter((item) => item.extension === "md");
  const otherFiles = files.filter((item) => item.extension !== "md");
  const hiddenCount =
    getOmittedDirectoryItemCount(folders) +
    getOmittedDirectoryItemCount(markdownFiles) +
    getOmittedDirectoryItemCount(otherFiles);

  return [
    `Referenced file: ${referencedFile.path}`,
    `Parent folder: ${formatVaultFolderLabel(folderPath)}`,
    "",
    "Exact direct children currently visible in the vault:",
    formatDirectorySection("Folders", folders.map((item) => item.path)),
    formatDirectorySection("Markdown files", markdownFiles.map((item) => item.path)),
    formatDirectorySection("Other files", otherFiles.map((item) => item.path)),
    hiddenCount > 0
      ? `Additional entries omitted from this listing: ${hiddenCount}`
      : "Additional entries omitted from this listing: 0",
    "",
    "This is a directory listing, not a list of inferred or likely files."
  ].join("\n");
}

function formatDirectorySection(label: string, paths: string[]): string {
  const visiblePaths = paths.slice(0, MAX_DIRECTORY_CONTEXT_ITEMS);
  if (visiblePaths.length === 0) {
    return `${label}:\n- (none)`;
  }

  return [
    `${label}:`,
    ...visiblePaths.map((item) => `- ${item}`)
  ].join("\n");
}

function getOmittedDirectoryItemCount(items: TAbstractFile[]): number {
  return Math.max(0, items.length - MAX_DIRECTORY_CONTEXT_ITEMS);
}

function compareVaultFiles(left: TAbstractFile, right: TAbstractFile): number {
  const leftFolder = left instanceof TFolder;
  const rightFolder = right instanceof TFolder;
  if (leftFolder !== rightFolder) {
    return leftFolder ? -1 : 1;
  }

  return left.path.localeCompare(right.path);
}
