import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. Source lives in src/. */";

const prod = process.argv[2] === "production";
const builtins = Array.from(new Set([
  ...builtinModules,
  ...builtinModules
    .filter((moduleName) => !moduleName.startsWith("node:"))
    .map((moduleName) => `node:${moduleName}`)
]));

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  logLevel: "info",
  minify: prod,
  outfile: "main.js",
  platform: "browser",
  sourcemap: prod ? false : "inline",
  target: "es2022",
  treeShaking: true
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
